import { useState } from 'react'
import './AlleyDetailsPage.css'

const mapsUrl = 'https://www.google.com/maps/search/?api=1&query=Sunset+Lanes%2C+123+Main+Street%2C+Los+Angeles%2C+CA+90012'

export default function AlleyDetailsPage({ onBack, onJoin }) {
  const [saved, setSaved] = useState(false)
  const directions = () => window.open(mapsUrl, '_blank', 'noopener,noreferrer')
  return <main className="details-page"><header className="details-header"><a className="brand finder-brand" href="#back" onClick={(e) => { e.preventDefault(); onBack() }}><span className="brand-mark"><i /><i /><i /></span>LANE CLUB</a><nav><button className="nav-active" onClick={onBack}>Find an alley</button><button>My reservations</button><button>Account</button></nav><div className="finder-user"><i>LC</i><span>Lane Club member</span></div></header><div className="details-shell"><button className="details-back" onClick={onBack}>← Back to bowling alleys</button><section className="details-photo"><button onClick={() => setSaved(!saved)}>{saved ? '♥ Saved' : '♡ Save alley'}</button><div className="photo-pins">● ● ●</div><div className="photo-lanes"><i /><i /><i /><i /><i /></div><strong>SUNSET LANES</strong></section><section className="details-layout"><article><div className="details-title"><div><p>LOS ANGELES · DOWNTOWN</p><h1>Sunset <em>Lanes.</em></h1><span>★ 4.8 (124 reviews) · 123 Main Street, Los Angeles</span></div><button onClick={directions}>Get directions ↗</button></div><div className="details-tags"><b>16 lanes</b><span>Late night</span><span>Food & drinks</span><span>Member favorite</span></div><hr /><section className="details-about"><h2>A local favorite,<br /><em>made for your week.</em></h2><p>Sunset Lanes is a neighborhood bowling alley with classic lanes, great snacks, and a relaxed atmosphere. Members get the freedom to reserve their lane ahead of time and make every week a bowling week.</p><div className="details-stats"><div><strong>16</strong><span>bookable lanes</span></div><div><strong>11 AM – 11 PM</strong><span>weekday hours</span></div><div><strong>12 AM</strong><span>Friday & Saturday</span></div></div></section><hr /><section className="details-amenities"><h2>What you'll find here</h2><div><article><b>◉</b><h3>Choose your lane</h3><p>Pick from available lanes whenever you make a reservation.</p></article><article><b>◌</b><h3>Food & drinks</h3><p>Full snack bar and drinks available while you bowl.</p></article><article><b>◒</b><h3>Open late</h3><p>Make plans after work or start your weekend early.</p></article></div></section></article><aside className="membership-box"><p>MONTHLY MEMBERSHIP</p><h2>Bowl more.<br /><em>Plan less.</em></h2><div className="membership-price"><strong>$20</strong><span>per month</span></div><ul><li>✓ Up to 4 reservation hours every week</li><li>✓ Split your hours any way you like</li><li>✓ Pick your preferred lane</li><li>✓ Reserve up to 7 days ahead</li></ul><button onClick={onJoin}>Start membership <span>→</span></button><small>Cancel anytime. No long-term commitment.</small></aside></section></div></main>
}
