import { useMemo, useState } from 'react'
import AccountMenu from '../components/AccountMenu'
import './FindAlleyPage.css'

const alleys = [
  { id: 1, name: 'Sunset Lanes', area: 'Downtown Los Angeles', distance: 1.2, price: 20, lanes: 16, rating: 4.8, reviews: 124, tags: ['Late night', 'Food & drinks'], color: 'sunset' },
  { id: 2, name: 'Highland Bowl', area: 'Highland Park', distance: 3.6, price: 25, lanes: 24, rating: 4.7, reviews: 98, tags: ['Classic lanes', 'Family friendly'], color: 'highland' },
  { id: 3, name: 'The Spare Room', area: 'Hollywood', distance: 4.1, price: 30, lanes: 12, rating: 4.9, reviews: 203, tags: ['Premium', 'Cocktails'], color: 'spare' },
  { id: 4, name: 'Pin Point Social', area: 'Koreatown', distance: 5, price: 18, lanes: 10, rating: 4.6, reviews: 76, tags: ['Best value', 'Open late'], color: 'pinpoint' },
]

export default function FindAlleyPage({ onBack, onSelect, member, onAccount, onLogout }) {
  const [query, setQuery] = useState('')
  const [price, setPrice] = useState('Any price')
  const [sort, setSort] = useState('Recommended')
  const [saved, setSaved] = useState([])
  const filtered = useMemo(() => alleys.filter(alley => alley.name.toLowerCase().includes(query.toLowerCase()) && (price === 'Any price' || alley.price <= Number(price.replace('$', '')))).sort((a, b) => sort === 'Lowest price' ? a.price - b.price : sort === 'Highest rated' ? b.rating - a.rating : sort === 'Nearest' ? a.distance - b.distance : b.rating - a.rating || a.distance - b.distance), [query, price, sort])
  const toggleSaved = (event, id) => { event.stopPropagation(); setSaved(items => items.includes(id) ? items.filter(value => value !== id) : [...items, id]) }
  return <main className="finder-page"><header className="finder-header"><a className="brand finder-brand" href="#dashboard" onClick={(event) => { event.preventDefault(); onBack() }}><span className="brand-mark"><i /><i /><i /></span>LANE CLUB</a><nav><button className="nav-active">Find an alley</button><button>My reservations</button><button onClick={onAccount}>Account</button></nav><AccountMenu member={member} onOpenSettings={onAccount} onLogout={onLogout} /></header><section className="finder-hero"><div className="finder-hero-inner"><p>MEMBERSHIP STARTS HERE</p><h1>Find your <em>home lane.</em></h1><span>Choose a nearby bowling alley and start reserving up to four hours every week.</span><div className="finder-search"><label>⌕ <input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search by alley name" /></label><button>Search</button></div></div></section><section className="finder-content"><aside className="finder-filters"><div className="filter-title"><h2>Filters</h2><button onClick={() => { setPrice('Any price'); setQuery('') }}>Clear all</button></div><div className="filter-block"><h3>Monthly membership</h3>{['Any price','$20','$25','$30'].map(item => <label key={item}><input type="radio" name="price" checked={price === item} onChange={() => setPrice(item)} /> <span>{item === 'Any price' ? item : `Up to ${item}/month`}</span></label>)}</div></aside><section className="alley-results"><div className="results-head"><div><strong>{filtered.length} bowling alleys near you</strong><span>Membership includes up to 4 reservation hours/week.</span></div><label>Sort by <select value={sort} onChange={event => setSort(event.target.value)}><option>Recommended</option><option>Lowest price</option><option>Highest rated</option><option>Nearest</option></select></label></div><div className="alley-card-grid">{filtered.map(alley => <article className="alley-card" key={alley.id} onClick={() => onSelect(alley)} role="button" tabIndex="0"><div className={`alley-photo ${alley.color}`}><span>● ● ●</span><button onClick={event => toggleSaved(event, alley.id)}>{saved.includes(alley.id) ? '♥' : '♡'}</button><small>{alley.distance} mi away</small></div><div className="alley-card-body"><div className="alley-title"><div><h2>{alley.name}</h2><p>⌖ {alley.area}</p></div><span>★ {alley.rating} <i>({alley.reviews})</i></span></div><div className="alley-meta"><b>{alley.lanes} lanes</b>{alley.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="alley-price"><div><strong>${alley.price}</strong><span>/ member / month</span></div><button onClick={event => { event.stopPropagation(); onSelect(alley) }}>View alley →</button></div></div></article>)}</div></section></section></main>
}
