import { useState } from 'react'
import './LaneManagementPage.css'

const initialLanes = Array.from({ length: 16 }, (_, index) => ({ id: index + 1, name: `Lane ${index + 1}`, status: index === 5 ? 'Maintenance' : index < 4 ? 'In use' : 'Available', reservation: index === 0 ? 'Maya Thompson · until 8:00 PM' : index === 1 ? 'James Wilson · until 8:30 PM' : index === 2 ? 'Walk-in party · until 7:45 PM' : index === 3 ? 'Jordan Lee · until 9:00 PM' : index === 5 ? 'Pinsetter inspection' : '' }))

export default function LaneManagementPage({ onBack }) {
  const [lanes, setLanes] = useState(initialLanes)
  const [filter, setFilter] = useState('All lanes')
  const [selected, setSelected] = useState(null)
  const [notice, setNotice] = useState('')
  const visible = lanes.filter(lane => filter === 'All lanes' || lane.status === filter)
  const updateStatus = (status) => {
    setLanes(lanes.map(lane => lane.id === selected.id ? { ...lane, status, reservation: status === 'Available' ? '' : lane.reservation } : lane))
    setSelected({ ...selected, status })
    setNotice(`${selected.name} is now marked ${status.toLowerCase()}.`)
  }
  return <main className="lanes-page"><aside className="lanes-nav"><a className="brand dash-brand" href="#home" onClick={(e) => { e.preventDefault(); onBack() }}><span className="brand-mark"><i /><i /><i /></span>LANE CLUB</a><div className="alley-switch"><span>SL</span><div><strong>Sunset Lanes</strong><small>Owner account</small></div><b>⌄</b></div><nav><button onClick={onBack}>▦ Overview</button><button>♙ Members <span>148</span></button><button>▤ Reservations</button><button className="selected">◫ Lanes</button><button>⚙ Settings</button></nav><button className="dash-logout" onClick={onBack}>← Log out</button></aside><section className="lanes-content"><header className="lanes-header"><div><p>LANE MANAGEMENT</p><h1>Your <em>lanes.</em></h1><span>Manage availability, active sessions, and maintenance status.</span></div><button className="lane-add" onClick={() => setNotice('New lane creation will be connected to your saved alley setup.')}>+ Add lane</button></header>{notice && <p className="lanes-notice">{notice}</p>}<div className="lanes-toolbar"><div className="lane-count"><strong>{lanes.length}</strong> total lanes <b>•</b> <span>{lanes.filter(l => l.status === 'Available').length} available now</span></div><div className="lane-filters">{['All lanes', 'Available', 'In use', 'Maintenance'].map(item => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="lanes-grid">{visible.map(lane => <button className={`lane-tile ${lane.status.toLowerCase().replace(' ', '-')}`} key={lane.id} onClick={() => setSelected(lane)}><small>LANE</small><strong>{String(lane.id).padStart(2, '0')}</strong><span className="lane-tile-status">{lane.status}</span><p>{lane.reservation || 'Ready for reservations'}</p></button>)}</div></section>{selected && <div className="lane-drawer-backdrop" onClick={() => setSelected(null)}><aside className="lane-drawer" onClick={e => e.stopPropagation()}><button className="drawer-close" onClick={() => setSelected(null)}>×</button><p>LANE DETAILS</p><h2>{selected.name}</h2><div className={`drawer-status ${selected.status.toLowerCase().replace(' ', '-')}`}>{selected.status}</div><div className="drawer-detail"><span>CURRENT ACTIVITY</span><strong>{selected.reservation || 'No active reservation'}</strong></div><div className="drawer-detail"><span>LANE TYPE</span><strong>Member & walk-in</strong></div><div className="status-controls"><p>Change status</p><button onClick={() => updateStatus('Available')}>Mark available</button><button onClick={() => updateStatus('Maintenance')}>Set maintenance</button><button onClick={() => updateStatus('In use')}>Mark in use</button></div><button className="edit-lane">Edit lane details</button></aside></div>}</main>
}
