import { useState } from 'react'
import './OwnerWalkInReservationPage.css'

export default function OwnerWalkInReservationPage({ onBack }) {
  const [paymentMethod, setPaymentMethod] = useState('cash')
  const [saved, setSaved] = useState(false)
  const [amount, setAmount] = useState('32.00')
  const submit = event => { event.preventDefault(); setSaved(true) }
  return <main className="walkin-page"><header><button onClick={onBack}>← Back to reservations</button><strong>LANE CLUB</strong><span>Owner checkout</span></header><section><p>WALK-IN RESERVATION</p><h1>Book a <em>walk-in.</em></h1><span>Owner-created reservations have no membership-hour limit.</span><form onSubmit={submit}><div className="walkin-grid"><label>Guest name<input required placeholder="Guest name" /></label><label>Phone number<input type="tel" placeholder="(555) 555-5555" /></label><label>Lane<select defaultValue="Lane 01">{Array.from({ length: 16 }, (_, index) => <option key={index}>Lane {String(index + 1).padStart(2, '0')}</option>)}</select></label><label>Start time<select defaultValue="5:00 PM">{['11:00 AM', '1:00 PM', '3:00 PM', '5:00 PM', '7:00 PM', '9:00 PM'].map(time => <option key={time}>{time}</option>)}</select></label><label>Duration<select defaultValue="2 hours"><option>1 hour</option><option>1.5 hours</option><option>2 hours</option><option>3 hours</option><option>4 hours</option></select></label><label>Charge amount<input type="number" min="0" step="0.01" value={amount} onChange={event => setAmount(event.target.value)} /></label></div><fieldset><legend>Payment method</legend><label><input type="radio" checked={paymentMethod === 'cash'} onChange={() => setPaymentMethod('cash')} /> Cash — collect in person</label><label><input type="radio" checked={paymentMethod === 'card'} onChange={() => setPaymentMethod('card')} /> Card — swipe or tap at the counter</label></fieldset>{paymentMethod === 'card' && <div className="card-notice">Card collection is ready for a Stripe Terminal connection. A real charge will be enabled after the alley connects its Stripe account and terminal reader.</div>}<button className="walkin-submit">{paymentMethod === 'cash' ? 'Save cash reservation' : 'Continue to card reader'} →</button>{saved && <p className="walkin-success">Walk-in reservation saved. {paymentMethod === 'cash' ? 'Record the cash received at the counter.' : 'Card payment is queued for the connected reader.'}</p>}</form></section></main>
}
