import './ReservationConfirmationPage.css'

export default function ReservationConfirmationPage({ alley, onDashboard, onReserve, member }) {
  const reservation = member.reservations?.at(-1) || { date: 'Fri 13', time: '5:00 PM', duration: 2, lane: 8 }
  const reservationDate = /^\d{4}-\d{2}-\d{2}$/.test(reservation.date || '') ? new Date(`${reservation.date}T12:00:00`) : null
  const dateDay = reservationDate ? reservationDate.toLocaleDateString(undefined, { weekday: 'short' }).toUpperCase() : reservation.date.split(' ')[0].toUpperCase()
  const dateNumber = reservationDate ? reservationDate.getDate() : reservation.date.split(' ')[1]
  const dateMonth = reservationDate ? reservationDate.toLocaleDateString(undefined, { month: 'long' }).toUpperCase() : ''
  const initials = alley.name.split(' ').map(word => word[0]).join('').slice(0, 2).toUpperCase()
  const mapsUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${alley.name}, ${alley.area}`)}`
  return <main className="confirmation-page"><header className="confirmation-header"><a className="brand finder-brand" href="#dashboard" onClick={(event) => { event.preventDefault(); onDashboard() }}><span className="brand-mark"><i /><i /><i /></span>LANE CLUB</a><div className="finder-user"><i>{member.name.slice(0, 2).toUpperCase()}</i><span>{member.name}</span></div></header><section className="confirmation-shell"><div className="confirmation-mark">✓</div><p>RESERVATION CONFIRMED</p><h1>Your lane is<br /><em>waiting.</em></h1><span className="confirmation-subtitle">We saved your spot at {alley.name}. Get ready to roll!</span><article className="confirmation-card"><header><div><b>{initials}</b><span><strong>{alley.name}</strong><small>{alley.area}</small></span></div><span className="confirmed-pill">Confirmed</span></header><div className="confirmation-time"><div><small>DATE</small><strong>{dateDay}</strong><b>{dateNumber}</b><span>{dateMonth}</span></div><div><small>TIME</small><strong>{reservation.time}</strong><span>{reservation.duration} hours</span></div><div><small>YOUR LANE</small><strong>Lane {String(reservation.lane).padStart(2, '0')}</strong><span>Member & walk-in lane</span></div></div><div className="confirmation-address"><span>⌖</span><p><strong>{alley.area}</strong><br />Arrive a few minutes early and check in at the front desk.</p><button onClick={() => window.open(mapsUrl, '_blank', 'noopener,noreferrer')}>Get directions ↗</button></div></article><div className="confirmation-actions"><button onClick={onDashboard}>Go to my dashboard <span>→</span></button><button onClick={onReserve}>Make another reservation</button></div><div className="confirmation-note"><b>✦</b><p><strong>You have {Math.max(0, 4 - member.usedHours)} hours left this week.</strong><br />Your four weekly reservation hours reset Monday at 12:00 AM.</p></div></section></main>
}
